package otdav.entities;
// Generated 30 juin 2019 11:35:09 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fees generated by hbm2java
 */
@Entity
@Table(name = "fees", catalog = "pi_otdav")
public class Fees implements java.io.Serializable {

	private int idFees;
	private WorkDeposit workDeposit;
	private Float montant;

	public Fees() {
	}

	public Fees(int idFees, WorkDeposit workDeposit) {
		this.idFees = idFees;
		this.workDeposit = workDeposit;
	}

	public Fees(int idFees, WorkDeposit workDeposit, Float montant) {
		this.idFees = idFees;
		this.workDeposit = workDeposit;
		this.montant = montant;
	}

	@Id

	@Column(name = "idFees", unique = true, nullable = false)
	public int getIdFees() {
		return this.idFees;
	}

	public void setIdFees(int idFees) {
		this.idFees = idFees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idWorkDeposit", nullable = false)
	public WorkDeposit getWorkDeposit() {
		return this.workDeposit;
	}

	public void setWorkDeposit(WorkDeposit workDeposit) {
		this.workDeposit = workDeposit;
	}

	@Column(name = "montant", precision = 12, scale = 0)
	public Float getMontant() {
		return this.montant;
	}

	public void setMontant(Float montant) {
		this.montant = montant;
	}

}
